### ISSUE TITLE
Uncaught Error: Using $this when not in object context

### ISSUE THREAD

**Issue by alphaonex86** [exussum12/xxhash#1]
This last line have bug, I use php 7.3:
        $file = tmpfile();
        fwrite($file, $input);
        rewind($file);

        return $this->hashStream($file);

**Comment by exussum12** [comment]
Hi. How are you calling the hash function ?

It looks like your calling it like V32::hash('string'); or similar ?

**Comment by alphaonex86** [comment]
Hi, yes. Maybe usage example into the README will be usefull

**Comment by exussum12** [comment]
Sure I will add that tomorrow :)

**Comment by exussum12** [comment]
Closing this, I've released a version which allows this to be called statically, and added some docs, thanks for raising the issue :)
